import "./globals.css";
import NavBar from "@/components/navbar/NavBar";
import Footer from "@/components/footer/Footer";
import { ThemeProvider } from "../context/ThemeContext";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
            <div className="container">
              <NavBar/>
              {children}
              <Footer/>
            </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
